name: magicio
channels:
  - conda-forge
  - default
dependencies:
  - astropy=5
  - python=3.11
  - ctapipe=0.19
  - eventio
  - corsikaio
  - zeromq
  - ipython
  - numba>=0.56
  - numpy>=1.22
  - numpydoc
  - pytest
  - pyyaml
  - scipy
  - zlib
  - pip
  - h5py
  - uproot=5